'use client';

import { useEffect, useRef, useState } from 'react';
import type { ToolCall, ToolResultMessage } from '@earendil-works/pi-ai';
import { CheckIcon, ShieldAlertIcon, XIcon } from 'lucide-react';
import { Button } from './button';
import type { AnswerOutcome } from './question-card';
import { cn } from './utils';

// The strings `requireApproval` (`@boring/agent/approval`) asks with and puts at the start of a denial result.
export const APPROVE = 'Approve';
export const DENY = 'Deny';
export const DENIED_PREFIX = 'Denied by the person.';

const REFUSALS: Record<string, string> = {
  denied: 'The host did not accept this answer.',
  conflict: 'This call was already decided.',
  'unknown-question': 'This call is no longer waiting for a decision.',
};

/** The arguments the call would run with, one line each. They come from the model's call itself: the card shows what will actually execute. */
export function describeArguments(call: ToolCall): { readonly name: string; readonly value: string }[] {
  return Object.entries(call.arguments as Record<string, unknown>).map(([name, value]) => {
    const text = typeof value === 'string' ? value : JSON.stringify(value) ?? '';
    return { name, value: text.length > 600 ? `${text.slice(0, 600)}…` : text };
  });
}

/**
 * The settled state. The wrapper records its decision in the call's details; a call that settled without one was never
 * decided (the run was stopped while it waited), so it is not shown as approved.
 */
function decisionOf(result: ToolResultMessage | undefined, decision: 'approved' | 'denied' | 'cancelled' | undefined): 'pending' | 'denied' | 'approved' | 'cancelled' {
  if (!result) return 'pending';
  if (decision) return decision;
  const text = result.content.map(part => part.type === 'text' ? part.text : '').join('');
  return result.isError && text.startsWith(DENIED_PREFIX) ? 'denied' : 'cancelled';
}

/** Human approval for a gated tool call: pending (Approve and Deny), then approved or denied. Answering uses the host's `answer`. */
export function ApprovalCard({ call, result, answer, questionId, summary, decision, live = false }: {
  readonly call: ToolCall;
  /** The question ID bound to this call's assistant entry (`derive` provides it); answers use it, never the bare call ID. */
  readonly questionId?: string | undefined;
  /** The decision `requireApproval` recorded in the call's details (`derive` finds it). Without one, a settled call shows as not decided. */
  readonly decision?: 'approved' | 'denied' | 'cancelled' | undefined;
  /** The one-line summary `requireApproval` published for this call (`derive` finds it). Shown first; the raw arguments are then collapsed under it. */
  readonly summary?: string | undefined;
  readonly result: ToolResultMessage | undefined;
  readonly answer?: ((callId: string, answer: string) => Promise<AnswerOutcome>) | undefined;
  /** The call is still being generated by the model: it cannot be decided yet. */
  readonly live?: boolean;
}) {
  const [sent, setSent] = useState<string | undefined>();
  const [sending, setSending] = useState<string | undefined>();
  const [refusal, setRefusal] = useState<string | undefined>();
  const mounted = useRef(true);
  useEffect(() => { mounted.current = true; return () => { mounted.current = false; }; }, []);
  const settled = decisionOf(result, decision);
  const state = settled !== 'pending' ? settled : sent === APPROVE ? 'approved-sent' : sent === DENY ? 'denied-sent' : 'pending';
  const args = describeArguments(call);
  const busy = sending !== undefined || live;

  async function decide(value: string) {
    if (!answer || !questionId || busy) return;
    setRefusal(undefined); setSending(value);
    try {
      const outcome = await answer(questionId, value);
      if (outcome.kind === 'answered') setSent(value);
      else setRefusal(outcome.reason || REFUSALS[outcome.kind] || 'The decision was refused.');
    } catch (cause) { setRefusal(cause instanceof Error ? cause.message : 'The decision could not be sent.'); }
    finally { if (mounted.current) setSending(undefined); }
  }
  const approved = state === 'approved' || state === 'approved-sent', denied = state === 'denied' || state === 'denied-sent';

  return <section data-testid="approval-card" data-state={state} data-call-id={call.id} data-tool={call.name} aria-label="Approval needed"
    className={cn('my-2 rounded-xl border bg-card p-4 text-card-foreground shadow-xs', state === 'pending' ? 'border-amber-500/60' : 'border-border')}>
    <div className="flex items-start gap-3">
      <span className={cn('mt-0.5 flex size-7 shrink-0 items-center justify-center rounded-full', state === 'pending' ? 'bg-amber-500/15 text-amber-600 dark:text-amber-400' : denied ? 'bg-destructive/10 text-destructive' : 'bg-muted text-muted-foreground')}>
        {approved ? <CheckIcon className="size-4" aria-hidden="true" /> : denied ? <XIcon className="size-4" aria-hidden="true" /> : <ShieldAlertIcon className="size-4" aria-hidden="true" />}
      </span>
      <div className="min-w-0 flex-1">
        <p className="m-0 text-[11px] font-medium tracking-wider text-muted-foreground uppercase">{state === 'pending' ? 'Needs your approval' : approved ? 'Approved' : denied ? 'Denied' : 'Not decided: the run was stopped'}</p>
        {summary && <p data-testid="approval-summary" className="mt-1 mb-0 text-base leading-6 font-semibold [overflow-wrap:anywhere]">{summary}</p>}
        <p data-testid="approval-tool" className={cn('mb-0 [overflow-wrap:anywhere]', summary ? 'mt-1 text-xs text-muted-foreground' : 'mt-1 text-[0.9375rem] leading-6 font-medium')}>The agent wants to run <code className="rounded bg-muted px-1.5 py-0.5 font-mono text-[0.8125rem]">{call.name}</code></p>
        {args.length > 0 && (() => {
          const list = <dl data-testid="approval-args" className="mt-2 mb-0 grid grid-cols-[auto_1fr] gap-x-3 gap-y-1 text-xs">
            {args.map(item => [<dt key={`${item.name}:n`} className="text-muted-foreground">{item.name}</dt>, <dd key={`${item.name}:v`} className="m-0 font-mono whitespace-pre-wrap [overflow-wrap:anywhere]">{item.value}</dd>])}
          </dl>;
          // With a summary the raw arguments are the detail behind it; without one they are all the person has to decide on.
          return summary ? <details data-testid="approval-details" className="mt-2 text-xs"><summary className="cursor-pointer text-muted-foreground select-none">Arguments</summary>{list}</details> : list;
        })()}
        {state === 'pending' && <>
          <div role="group" aria-label="Decision" className="mt-3 flex flex-wrap gap-2">
            <Button variant="default" data-testid="approval-approve" disabled={!answer || !questionId || busy} onClick={() => { void decide(APPROVE); }} className={cn('min-h-11 sm:min-h-9', sending === APPROVE && 'opacity-70')}><CheckIcon className="size-3.5" aria-hidden="true" />Approve</Button>
            <Button variant="outline" data-testid="approval-deny" disabled={!answer || !questionId || busy} onClick={() => { void decide(DENY); }} className={cn('min-h-11 sm:min-h-9', sending === DENY && 'border-ring')}><XIcon className="size-3.5" aria-hidden="true" />Deny</Button>
          </div>
          {live && <p className="mt-3 mb-0 text-xs text-muted-foreground">The agent is still writing this call…</p>}
          {(!answer || !questionId) && !live && <p className="mt-3 mb-0 text-xs text-muted-foreground">Deciding is not available in this view.</p>}
        </>}
        {(state === 'approved-sent' || state === 'denied-sent') && <p className="mt-2 mb-0 text-xs text-muted-foreground">{approved ? 'Approved.' : 'Denied.'} Waiting for the agent…</p>}
        {refusal && state === 'pending' && <p role="alert" data-testid="approval-refusal" className="mt-3 mb-0 rounded-md bg-destructive/10 px-3 py-2 text-sm text-destructive">{refusal}</p>}
      </div>
    </div>
  </section>;
}
