'use client';

import { useEffect, useRef, useState } from 'react';
import type { FormEvent } from 'react';
import type { ToolCall, ToolResultMessage } from '@earendil-works/pi-ai';
import { CheckIcon, MessageCircleQuestionIcon, SendIcon } from 'lucide-react';
import { Button } from '../button/button';
import { cn } from '../utils/utils';
import { useChatText } from './labels';

/** What the host answers when asked to resolve a pending question. */
export type AnswerOutcome = { readonly kind: 'answered' } | { readonly kind: 'denied' | 'conflict' | 'unknown-question'; readonly reason?: string };
export const ASK_USER_TOOL = 'ask_user';

interface Question { readonly question: string; readonly options: readonly string[]; readonly allowFreeText: boolean }

/** Read `{ question, options?, allowFreeText? }` defensively: model arguments are untrusted input. */
export function parseQuestion(call: ToolCall): Question {
  const args = call.arguments as Record<string, unknown>;
  const options = Array.isArray(args['options']) ? args['options'].filter((item): item is string => typeof item === 'string' && item.length > 0).slice(0, 6) : [];
  return { question: typeof args['question'] === 'string' ? args['question'] : '', options, allowFreeText: args['allowFreeText'] === true };
}

/** The answered text from a result such as `{"kind":"answered","answer":"..."}`; undefined when the call did not produce an answer. */
export function parseAnswer(result: ToolResultMessage | undefined): { readonly answer: string } | { readonly failure: string } | undefined {
  if (!result) return undefined;
  const text = result.content.map(part => part.type === 'text' ? part.text : '').join('');
  if (!result.isError) {
    try {
      const value: unknown = JSON.parse(text);
      if (value !== null && typeof value === 'object' && (value as { kind?: unknown }).kind === 'answered' && typeof (value as { answer?: unknown }).answer === 'string') return { answer: (value as { answer: string }).answer };
    } catch { /* fall through to the failure text */ }
  }
  return { failure: text || 'The question was not answered.' };
}


/** Human-in-the-loop question: writing (still generated, not answerable), pending (options and optional free text), then answered with the chosen answer. */
export function QuestionCard({ call, result, answer, questionId, live = false }: {
  readonly call: ToolCall;
  readonly result: ToolResultMessage | undefined;
  readonly questionId: string | undefined;
  readonly answer?: ((questionId: string, answer: string) => Promise<AnswerOutcome>) | undefined;
  /** The call is still being generated by the model: it cannot be answered yet. */
  readonly live?: boolean;
}) {
  const { labels } = useChatText();
  const question = parseQuestion(call);
  const settled = parseAnswer(result);
  const [sent, setSent] = useState<string | undefined>();
  const [sending, setSending] = useState<string | undefined>();
  const [refusal, setRefusal] = useState<string | undefined>();
  const [text, setText] = useState('');
  const mounted = useRef(true);
  useEffect(() => { mounted.current = true; return () => { mounted.current = false; }; }, []);
  const current = settled && 'answer' in settled ? settled.answer : sent;
  // `pending` means the question waits on the person; `writing` means the model is still generating it (options may be partial).
  const state = settled ? ('failure' in settled ? 'failed' : 'answered') : sent !== undefined ? 'sent' : live ? 'writing' : 'pending';
  const open = state === 'pending' || state === 'writing';

  async function submit(value: string) {
    const trimmed = value.trim();
    if (!answer || !questionId || live || !trimmed || sending !== undefined) return;
    setRefusal(undefined); setSending(trimmed);
    try {
      const outcome = await answer(questionId, trimmed);
      if (outcome.kind === 'answered') setSent(trimmed);
      else setRefusal(outcome.reason || labels.answerRefused(outcome.kind));
    } catch (cause) { setRefusal(cause instanceof Error ? cause.message : labels.answerNotSent); }
    finally { if (mounted.current) setSending(undefined); }
  }
  const onSubmit = (event: FormEvent) => { event.preventDefault(); void submit(text); };
  const busy = sending !== undefined || live;

  return <section data-testid="question-card" data-state={state} data-call-id={call.id} aria-label={labels.question}
    className={cn('my-2 rounded-xl border bg-card p-4 text-card-foreground shadow-xs', open ? 'border-ring/50' : 'border-border')}>
    <div className="flex items-start gap-3">
      <span className={cn('mt-0.5 flex size-7 shrink-0 items-center justify-center rounded-full', open ? 'bg-primary text-primary-foreground' : 'bg-muted text-muted-foreground')}>
        {state === 'answered' || state === 'sent' ? <CheckIcon className="size-4" aria-hidden="true" /> : <MessageCircleQuestionIcon className="size-4" aria-hidden="true" />}
      </span>
      <div className="min-w-0 flex-1">
        <p className="m-0 text-[11px] font-medium tracking-wider text-muted-foreground uppercase">{open ? labels.questionForYou : state === 'failed' ? labels.notAnswered : labels.answered}</p>
        <p data-testid="question-text" className="mt-1 mb-0 text-[0.9375rem] leading-6 font-medium [overflow-wrap:anywhere]">{question.question || labels.askedQuestion}</p>

        {open && <>
          {question.options.length > 0 && <div role="group" aria-label={labels.answerOptions} className="mt-3 flex flex-wrap gap-2">
            {question.options.map(option => <Button key={option} variant="outline" data-testid="question-option" data-option={option} disabled={!answer || !questionId || busy}
              onClick={() => { void submit(option); }} className={cn('h-auto min-h-11 max-w-full py-1.5 whitespace-normal sm:min-h-9', sending === option && 'border-ring')}>{option}</Button>)}
          </div>}
          {question.allowFreeText && <form onSubmit={onSubmit} className="mt-3 flex gap-2">
            <input data-testid="question-input" value={text} maxLength={2000} disabled={!answer || !questionId || busy} placeholder={question.options.length ? labels.ownAnswer : labels.typeAnswer}
              aria-label={labels.yourAnswerInput} onChange={event => setText(event.currentTarget.value)}
              className="h-11 min-w-0 flex-1 rounded-lg border border-input bg-background px-3 text-base outline-none sm:h-9 sm:text-sm placeholder:text-muted-foreground focus-visible:ring-2 focus-visible:ring-ring/60 disabled:opacity-50" />
            <Button type="submit" variant="default" data-testid="question-submit" disabled={!answer || !questionId || busy || !text.trim()}><SendIcon className="size-3.5" aria-hidden="true" />{labels.answer}</Button>
          </form>}
          {live && <p className="mt-3 mb-0 text-xs text-muted-foreground">{labels.stillWritingQuestion}</p>}
          {!answer && !live && <p className="mt-3 mb-0 text-xs text-muted-foreground">{labels.answeringUnavailable}</p>}
        </>}

        {(state === 'answered' || state === 'sent') && current !== undefined && <p className="mt-2 mb-0 text-sm text-muted-foreground">{labels.yourAnswer} <span data-testid="question-answer" className="rounded-md bg-muted px-1.5 py-0.5 font-medium text-foreground [overflow-wrap:anywhere]">{current}</span>
          {state === 'sent' && <span className="ms-2 text-xs">{labels.waitingForAgent}</span>}</p>}
        {state === 'failed' && settled && 'failure' in settled && <p role="alert" className="mt-2 mb-0 text-sm text-destructive">{settled.failure}</p>}
        {refusal && open && <p role="alert" data-testid="question-refusal" className="mt-3 mb-0 rounded-md bg-destructive/10 px-3 py-2 text-sm text-destructive">{refusal}</p>}
      </div>
    </div>
  </section>;
}
